import XCTest
import SwiftUI
@testable import SketchyBarSettings

final class TemplateRendererTests: XCTestCase {
    func testRenderIncludesEnabledWidgets() throws {
        let input = RenderInput(
            bar: BarSettings(),
            widgets: WidgetConfig.defaults
        )
        let output = try TemplateRenderer.render(input)

        XCTAssertTrue(output.contains("sketchybar --add item date center"))
        XCTAssertTrue(output.contains("sketchybar --add item clock center"))
        XCTAssertTrue(output.contains("sketchybar --add item spotify center"))
        XCTAssertTrue(output.contains("sketchybar --add item spotify_cover center"))
        XCTAssertTrue(output.contains("sketchybar --add bracket spotify_group spotify_cover spotify"))
        let centerBracket = output.components(separatedBy: "sketchybar --add bracket center_status").dropFirst().first ?? ""
        XCTAssertTrue(centerBracket.contains("spotify_cover"))
        XCTAssertFalse(centerBracket.hasPrefix(" spotify_group") || centerBracket.contains(" center_status spotify_group"))
        XCTAssertFalse(output.contains("sketchybar --add bracket center_status") && centerBracket.split(separator: "\n").first?.contains("spotify_group") == true)
    }

    func testRenderOmitsDisabledWidgets() throws {
        var widgets = WidgetConfig.defaults
        widgets[0].enabled = false
        let input = RenderInput(bar: BarSettings(), widgets: widgets)
        let output = try TemplateRenderer.render(input)

        XCTAssertFalse(output.contains("sketchybar --add item date center"))
        XCTAssertTrue(output.contains("sketchybar --add item clock center"))
    }

    func testRenderRespectsPlacementAndOrder() throws {
        var widgets = WidgetConfig.defaults
        widgets = widgets.map { widget in
            var w = widget
            if w.id == "battery" {
                w.placement = .right
                w.order = 0
            }
            if w.id == "volume" {
                w.placement = .right
                w.order = 1
            }
            return w
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        XCTAssertTrue(output.contains("sketchybar --add item battery right"))
        XCTAssertTrue(output.contains("sketchybar --add bracket status battery volume"))
    }

    func testRenderUsesBarSettings() throws {
        var bar = BarSettings()
        bar.height = 48
        bar.yOffset = 6
        bar.backgroundHex = "0xFF112233"
        bar.shadow = true

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("height=48"))
        XCTAssertTrue(output.contains("y_offset=6"))
        XCTAssertTrue(output.contains("color=0xFF112233"))
        XCTAssertTrue(output.contains("shadow=on"))
    }

    func testRenderAppliesOpaqueBarBackgroundHex() throws {
        var bar = BarSettings()
        bar.backgroundHex = "0xFF336699"

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("color=0xFF336699"))
    }

    func testRenderLoadsTemplateFromBundleAndAppliesBarValues() throws {
        var bar = BarSettings()
        bar.height = 52
        bar.yOffset = 8
        bar.backgroundHex = "0xFFABCDEF"

        let output = try TemplateRenderer.render(
            RenderInput(bar: bar, widgets: WidgetConfig.defaults)
        )

        XCTAssertTrue(output.contains("height=52"))
        XCTAssertTrue(output.contains("y_offset=8"))
        XCTAssertTrue(output.contains("color=0xFFABCDEF"))
        XCTAssertTrue(output.contains("# Generated by SketchyBar Settings. DO NOT EDIT BY HAND."))
    }

    func testRenderAppliesValuesFromCustomTemplate() throws {
        let loader = StringTemplateLoader(template: """
        BAR={{BAR_HEIGHT}}
        SHADOW={{BAR_SHADOW}}
        {{WIDGET_BLOCKS}}
        """)

        var bar = BarSettings()
        bar.height = 44
        bar.shadow = true

        let output = try TemplateRenderer.render(
            RenderInput(bar: bar, widgets: []),
            loader: loader
        )

        XCTAssertEqual(output, "BAR=44\nSHADOW=on\n")
    }

    func testRenderFailsWhenTemplateMissing() {
        struct MissingTemplateLoader: TemplateLoading {
            func loadTemplate(named name: String) throws -> String {
                throw TemplateRenderError.templateNotFound(name)
            }
        }

        XCTAssertThrowsError(
            try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: []), loader: MissingTemplateLoader())
        ) { error in
            XCTAssertEqual(error as? TemplateRenderError, .templateNotFound("sketchybarrc.template"))
        }
    }
}

final class SettingsStoreTests: XCTestCase {
    private var suiteName = ""
    private var defaults: UserDefaults!
    private var store: SettingsStore!

    override func setUp() {
        super.setUp()
        suiteName = "SketchyBarSettingsTests.\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suiteName)!
        store = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )
    }

    override func tearDown() {
        defaults.removePersistentDomain(forName: suiteName)
        store = nil
        defaults = nil
        super.tearDown()
    }

    func testTogglePersists() {
        let id = "date"
        let initial = store.widget(id: id)?.enabled ?? true
        store.toggle(id)

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.widget(id: id)?.enabled, !initial)
    }

    private func keepOnlyEnabled(ids: [String]) {
        for widget in store.widgets {
            let shouldEnable = ids.contains(widget.id)
            if widget.enabled != shouldEnable {
                store.toggle(widget.id)
            }
        }
        for id in ids {
            store.setPlacement(id, .center)
        }
    }

    func testMoveChangesOrderWithinPlacement() {
        keepOnlyEnabled(ids: ["date", "clock"])

        let before = store.widgets(in: .center).map(\.id)
        store.move("clock", up: true)
        let after = store.widgets(in: .center).map(\.id)

        XCTAssertNotEqual(before, after)
        XCTAssertEqual(after.first, "clock")
    }

    func testSetPlacementAppendsToEnd() {
        store.setPlacement("date", .center)
        store.setPlacement("clock", .center)
        store.setPlacement("battery", .right)

        store.setPlacement("date", .right)

        let rightOrder = store.widgets(in: .right).map(\.id)
        XCTAssertEqual(rightOrder.last, "date")
    }

    func testReorderWidgetMovesWithinPlacement() {
        keepOnlyEnabled(ids: ["date", "clock", "ai_usage"])

        store.reorderWidget(id: "ai_usage", toIndex: 0, in: .center)

        XCTAssertEqual(store.widgets(in: .center).map(\.id).first, "ai_usage")
    }

    func testMoveWidgetBeforeInsertsAtTarget() {
        keepOnlyEnabled(ids: ["date", "clock", "ai_usage"])

        store.moveWidgetBefore("ai_usage", targetID: "clock")

        XCTAssertEqual(store.widgets(in: .center).map(\.id), ["date", "ai_usage", "clock"])
    }

    func testMoveWidgetBeforeIgnoresDifferentPlacement() {
        store.setPlacement("date", .center)
        store.setPlacement("battery", .right)

        let beforeDate = store.widget(id: "date")?.placement
        store.moveWidgetBefore("date", targetID: "battery")

        XCTAssertEqual(store.widget(id: "date")?.placement, beforeDate)
    }

    func testResetToDefaults() {
        store.bar.height = 99
        store.toggle("date")
        store.resetToDefaults()

        XCTAssertEqual(store.bar.height, BarSettings().height)
        XCTAssertTrue(store.widget(id: "date")?.enabled ?? false)
    }

    func testUpdateBarBackgroundHexPersists() {
        store.updateBarBackgroundHex("0xFFC97C5D")

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.bar.backgroundHex, "0xFFC97C5D")
    }

    func testPresetBarBackgroundFlowsToRenderer() throws {
        store.updateBarBackgroundHex("0xFFC97C5D")

        let output = try TemplateRenderer.render(store.renderInput)
        XCTAssertTrue(output.contains("color=0xFFC97C5D"))
    }

    func testWidgetBackgroundPresetFlowsToRenderer() throws {
        store.select("date")
        store.updateSelectedWidgetBackground(enabled: true)
        store.updateSelectedWidgetBackgroundHex("0xFF87986A")

        let output = try TemplateRenderer.render(store.renderInput)
        XCTAssertTrue(output.contains("background.drawing=on"))
        XCTAssertTrue(output.contains("background.color=\"0xFF87986A\""))
    }

    func testMigrateWidgetBackgroundForLegacyData() {
        let legacyWidgets: [[String: Any]] = WidgetConfig.defaults.map { widget in
            [
                "id": widget.id,
                "name": widget.name,
                "enabled": widget.enabled,
                "placement": widget.placement.rawValue,
                "order": widget.order,
                "showIcon": widget.showIcon,
            ]
        }
        let legacyJSON: [String: Any] = [
            "bar": [
                "height": 40,
                "yOffset": 4,
                "cornerRadius": 14,
                "backgroundHex": "0x00000000",
                "shadow": false,
                "paddingLeft": 3,
                "paddingRight": 3,
                "itemSpacing": 6,
                "spotifyCoverSize": 28,
            ],
            "widgets": legacyWidgets,
        ]
        let data = try! JSONSerialization.data(withJSONObject: legacyJSON)
        defaults.set(data, forKey: "test.settings")

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.widget(id: "spotify")?.backgroundEnabled, true)
        XCTAssertEqual(reloaded.widget(id: "spotify")?.backgroundHex, WidgetConfig.panelBackgroundHex)
        XCTAssertEqual(reloaded.widget(id: "date")?.backgroundHex, WidgetConfig.panelBackgroundHex)
    }

    func testMigrateWidgetColorForLegacyData() {
        let legacyWidgets: [[String: Any]] = WidgetConfig.defaults.map { widget in
            [
                "id": widget.id,
                "name": widget.name,
                "enabled": widget.enabled,
                "placement": widget.placement.rawValue,
                "order": widget.order,
                "showIcon": widget.showIcon,
                "backgroundEnabled": widget.backgroundEnabled,
                "backgroundHex": widget.backgroundHex as Any,
            ]
        }
        let legacyJSON: [String: Any] = [
            "bar": [
                "height": 40,
                "yOffset": 4,
                "cornerRadius": 14,
                "backgroundHex": "0x00000000",
                "shadow": false,
                "paddingLeft": 3,
                "paddingRight": 3,
                "itemSpacing": 6,
                "spotifyCoverSize": 28,
            ],
            "widgets": legacyWidgets,
        ]
        let data = try! JSONSerialization.data(withJSONObject: legacyJSON)
        defaults.set(data, forKey: "test.settings")

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.widget(id: "date")?.colorHex, EarthColorCatalog.sand)
        XCTAssertNil(reloaded.widget(id: "umi_icon")?.colorHex)
    }

    func testApplyRecommendedWidgetColorHexOnlyWhenMissing() {
        store.select("date")
        store.updateSelectedWidget { $0.colorHex = "0xFF112233" }

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.widget(id: "date")?.colorHex, "0xFF112233")
        XCTAssertEqual(reloaded.widget(id: "clock")?.colorHex, EarthColorCatalog.terracotta)
    }

    func testLegacyJSONDecodePreservesBarNumericValues() {
        let legacyJSON: [String: Any] = [
            "bar": [
                "height": 52,
                "yOffset": 8,
                "cornerRadius": 18,
                "backgroundHex": "0xFF112233",
                "shadow": true,
                "paddingLeft": 5,
                "paddingRight": 7,
                "itemSpacing": 10,
            ],
            "widgets": WidgetConfig.defaults.map { widget in
                [
                    "id": widget.id,
                    "name": widget.name,
                    "enabled": widget.enabled,
                    "placement": widget.placement.rawValue,
                    "order": widget.order,
                    "showIcon": widget.showIcon,
                ] as [String: Any]
            },
        ]
        let data = try! JSONSerialization.data(withJSONObject: legacyJSON)
        defaults.set(data, forKey: "test.settings")

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.bar.height, 52)
        XCTAssertEqual(reloaded.bar.yOffset, 8)
        XCTAssertEqual(reloaded.bar.cornerRadius, 18)
        XCTAssertEqual(reloaded.bar.paddingLeft, 5)
        XCTAssertEqual(reloaded.bar.paddingRight, 7)
        XCTAssertEqual(reloaded.bar.itemSpacing, 10)
        XCTAssertEqual(reloaded.bar.spotifyCoverSize, 28)
        XCTAssertEqual(reloaded.bar.fontFamily, FontFamilies.defaultFamily)
        XCTAssertEqual(reloaded.bar.fontSize, 13)
    }

    func testAllNumericValuesPersistAcrossReload() {
        store.bar.height = 48
        store.bar.yOffset = 6
        store.bar.cornerRadius = 16
        store.bar.paddingLeft = 8
        store.bar.paddingRight = 9
        store.bar.itemSpacing = 12
        store.bar.widgetPadding = 6
        store.bar.spotifyCoverSize = 36
        store.bar.fontSize = 15
        store.save()

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.bar.height, 48)
        XCTAssertEqual(reloaded.bar.yOffset, 6)
        XCTAssertEqual(reloaded.bar.cornerRadius, 16)
        XCTAssertEqual(reloaded.bar.paddingLeft, 8)
        XCTAssertEqual(reloaded.bar.paddingRight, 9)
        XCTAssertEqual(reloaded.bar.itemSpacing, 12)
        XCTAssertEqual(reloaded.bar.widgetPadding, 6)
        XCTAssertEqual(reloaded.bar.spotifyCoverSize, 36)
        XCTAssertEqual(reloaded.bar.fontSize, 15)
    }

    func testApplyStylePresetPersists() {
        let preset = EarthColorCatalog.stylePresets.first { $0.id == "dune" }!
        let originalBarHex = store.bar.backgroundHex
        store.applyStylePreset(preset, applyCardBackgrounds: true)

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        XCTAssertEqual(reloaded.bar.backgroundHex, originalBarHex)
        XCTAssertEqual(reloaded.bar.selectedStylePresetID, preset.id)
        XCTAssertEqual(reloaded.widget(id: "clock")?.colorHex, preset.textHex)
        XCTAssertEqual(reloaded.widget(id: "date")?.colorHex, preset.mutedTextHex)
        XCTAssertEqual(reloaded.widget(id: "date")?.backgroundEnabled, true)
        XCTAssertEqual(reloaded.widget(id: "date")?.backgroundHex, preset.cardBackgroundHex)
    }

    func testApplyStylePresetWithoutCardBackgrounds() {
        let preset = EarthColorCatalog.stylePresets.first { $0.id == "forest" }!
        store.select("clock")
        store.updateSelectedWidgetBackground(enabled: false)

        store.applyStylePreset(preset, applyCardBackgrounds: false)

        XCTAssertEqual(store.widget(id: "clock")?.backgroundEnabled, false)
        XCTAssertEqual(store.widget(id: "clock")?.colorHex, preset.textHex)
        XCTAssertEqual(store.widget(id: "clock")?.backgroundHex, preset.cardBackgroundHex)
        XCTAssertEqual(store.bar.backgroundHex, BarSettings().backgroundHex)
    }

    func testApplyStylePresetLeavesCustomBarBackgroundUnchanged() {
        store.updateBarBackgroundHex("0xFF112233")
        let preset = EarthColorCatalog.stylePresets.first { $0.id == "terracotta" }!
        store.applyStylePreset(preset, applyCardBackgrounds: true)

        XCTAssertEqual(store.bar.backgroundHex, "0xFF112233")
        XCTAssertEqual(store.widget(id: "volume")?.colorHex, preset.textHex)
        XCTAssertEqual(store.widget(id: "volume")?.backgroundHex, preset.cardBackgroundHex)
        XCTAssertEqual(store.widget(id: "volume")?.backgroundEnabled, true)
        XCTAssertEqual(store.bar.selectedStylePresetID, preset.id)
    }

    func testDecodeFailureDoesNotSilentlyOverwriteInSameSession() {
        defaults.set(Data("not json".utf8), forKey: "test.settings")

        let reloaded = SettingsStore(
            defaults: defaults,
            defaultsKey: "test.settings",
            configPath: "/tmp/sketchybar-test/sketchybarrc",
            pluginsDir: "/tmp/sketchybar-test/plugins"
        )

        if case .decodeFailed = reloaded.lastLoadError {
            // expected
        } else {
            XCTFail("decode error expected")
        }
    }
}

final class SketchyBarColorHexTests: XCTestCase {
    func testParseValidARGB() {
        let components = SketchyBarColorHex.parse("0xFF112233")
        XCTAssertEqual(components?.a, 255)
        XCTAssertEqual(components?.r, 0x11)
        XCTAssertEqual(components?.g, 0x22)
        XCTAssertEqual(components?.b, 0x33)
    }

    func testParseValidRGBAssumesOpaqueAlpha() {
        let components = SketchyBarColorHex.parse("0x112233")
        XCTAssertEqual(components?.a, 255)
        XCTAssertEqual(components?.r, 0x11)
    }

    func testParseTransparentAlpha() {
        let components = SketchyBarColorHex.parse("0x80112233")
        XCTAssertEqual(components?.a, 0x80)
    }

    func testSanitizedRejectsInvalidHex() {
        XCTAssertEqual(
            SketchyBarColorHex.sanitized("not-a-color", fallback: "0x00000000"),
            "0x00000000"
        )
    }

    func testFormatRoundTrip() {
        let formatted = SketchyBarColorHex.format((a: 128, r: 1, g: 2, b: 3))
        XCTAssertEqual(formatted, "0x80010203")
        XCTAssertEqual(SketchyBarColorHex.parse(formatted)?.a, 128)
    }

    func testHexFromColorPreservesARGB() {
        let color = Color(
            .sRGB,
            red: 51.0 / 255.0,
            green: 102.0 / 255.0,
            blue: 153.0 / 255.0,
            opacity: 1.0
        )
        XCTAssertEqual(SketchyBarColorHex.hex(from: color), "0xFF336699")
    }

    func testColorFromHexPreservesAlpha() {
        let color = SketchyBarColorHex.color(from: "0x80336699")
        XCTAssertEqual(SketchyBarColorHex.hex(from: color), "0x80336699")
    }
}

final class TemplateRendererStyleTests: XCTestCase {
    func testRenderUsesCustomFontFamily() throws {
        var bar = BarSettings()
        bar.fontFamily = "Helvetica Neue"
        bar.fontSize = 15

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("label.font=\"Helvetica Neue:Medium:15.0\""))
    }

    func testRenderUsesGlobalFontForAllWidgets() throws {
        var bar = BarSettings()
        bar.fontFamily = "SF Pro Text"
        bar.fontSize = 13

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("label.font=\"SF Pro Text:Medium:13.0\""))
    }

    func testRenderIgnoresLegacyWidgetFontFamily() throws {
        var bar = BarSettings()
        bar.fontFamily = "SF Pro Text"
        bar.fontSize = 13

        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "date" }) {
            widgets[index].fontFamily = "UDEV Gothic 35JPDOC"
            widgets[index].fontSize = 20
        }

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let expectedFont = "SF Pro Text:Medium:13.0"
        let dateBlock = itemBlock(in: output, id: "date")

        XCTAssertTrue(dateBlock.contains("label.font=\"\(expectedFont)\""))
        XCTAssertTrue(dateBlock.contains("icon.font=\"\(expectedFont)\""))
        XCTAssertFalse(output.contains("UDEV Gothic"))
        XCTAssertFalse(output.contains(":20.0"))

        let itemIDs = ["date", "clock", "ai_usage", "volume", "audio_output", "spotify_cover", "spotify"]
        for id in itemIDs {
            let block = itemBlock(in: output, id: id)
            XCTAssertTrue(block.contains("label.font=\"\(expectedFont)\""), id)
            XCTAssertTrue(block.contains("icon.font=\"\(expectedFont)\""), id)
        }

        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: widgets))
        XCTAssertEqual(layout.fontFamily, "SF Pro Text")
        XCTAssertEqual(layout.fontSize, 13)
        XCTAssertEqual(Set(layout.allWidgets.map(\.fontFamily)), ["SF Pro Text"])
        XCTAssertEqual(Set(layout.allWidgets.map(\.fontSize)), [13])
    }

    private func itemBlock(in output: String, id: String) -> String {
        let marker = "sketchybar --add item \(id) "
        guard let start = output.range(of: marker) else { return "" }
        let fromStart = output[start.lowerBound...]
        let afterMarker = fromStart.dropFirst(marker.count)
        if let next = afterMarker.range(of: "\nsketchybar --add ") {
            return String(fromStart[..<next.lowerBound])
        }
        return String(fromStart)
    }

    func testRenderAppliesGlobalWidgetPadding() throws {
        var bar = BarSettings()
        bar.widgetPadding = 8

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        let dateBlock = output.components(separatedBy: "sketchybar --add item date center").dropFirst().first ?? ""
        XCTAssertTrue(dateBlock.contains("label.padding_left=8"))
        XCTAssertTrue(dateBlock.contains("label.padding_right=8"))
        XCTAssertFalse(dateBlock.contains("background.padding_left"))
        XCTAssertFalse(dateBlock.contains("background.padding_right"))
    }

    func testRenderItemSpacingDoesNotDoubleWithWidgetPadding() throws {
        var bar = BarSettings()
        bar.widgetPadding = 4
        bar.itemSpacing = 8

        var widgets = WidgetConfig.defaults
        widgets = widgets.filter { $0.id == "date" || $0.id == "clock" }
        for index in widgets.indices {
            widgets[index].backgroundEnabled = true
        }

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let dateBlock = output.components(separatedBy: "sketchybar --add item date center").dropFirst().first ?? ""
        let clockBlock = output.components(separatedBy: "sketchybar --add item clock center").dropFirst().first ?? ""

        XCTAssertTrue(dateBlock.contains("padding_left=0"))
        XCTAssertTrue(dateBlock.contains("padding_right=8"))
        XCTAssertTrue(dateBlock.contains("label.padding_left=4"))
        XCTAssertTrue(dateBlock.contains("label.padding_right=4"))
        XCTAssertFalse(dateBlock.contains("background.padding_left"))
        XCTAssertTrue(clockBlock.contains("padding_left=0"))
        XCTAssertTrue(clockBlock.contains("padding_right=0"))
        XCTAssertTrue(clockBlock.contains("label.padding_left=4"))

        let dateOuter = ItemLayoutMetrics.outerPadding(itemSpacing: 8, isFirst: true, isLast: false)
        let clockOuter = ItemLayoutMetrics.outerPadding(itemSpacing: 8, isFirst: false, isLast: true)
        XCTAssertEqual(ItemLayoutMetrics.gapBetweenCards(leftOuter: dateOuter, rightOuter: clockOuter), 8)
    }

    func testRenderAppliesWhiteColor() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "clock" }) {
            widgets[index].colorHex = EarthColorCatalog.white
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let block = output.components(separatedBy: "sketchybar --add item clock center").dropFirst().first ?? ""
        XCTAssertTrue(block.contains("label.color=\"0xFFFFFFFF\""))
        XCTAssertTrue(block.contains("icon.color=\"0xFFFFFFFF\""))
    }

    func testRenderSpotifyGroupPaddingAndBracket() throws {
        var bar = BarSettings()
        bar.widgetPadding = 6
        bar.itemSpacing = 10

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        let coverBlock = output.components(separatedBy: "sketchybar --add item spotify_cover").dropFirst().first ?? ""
        let spotifyBlock = output.components(separatedBy: "sketchybar --add item spotify center").dropFirst().first ?? ""
        let groupBlock = output.components(separatedBy: "sketchybar --add bracket spotify_group").dropFirst().first ?? ""

        XCTAssertTrue(coverBlock.contains("padding_left=6"))
        XCTAssertTrue(coverBlock.contains("padding_right=0"))
        XCTAssertTrue(coverBlock.contains("background.drawing=on"))
        XCTAssertTrue(coverBlock.contains("background.color=\"0x00000000\""))
        XCTAssertTrue(spotifyBlock.contains("label.padding_right=6"))
        XCTAssertTrue(spotifyBlock.contains("padding_right=0"))
        XCTAssertTrue(spotifyBlock.contains("background.drawing=off"))
        XCTAssertFalse(groupBlock.contains("background.padding_left"))
        XCTAssertFalse(groupBlock.contains("background.padding_right"))
        XCTAssertTrue(groupBlock.contains("background.height=32"))
        XCTAssertTrue(output.contains("sketchybar --add bracket center_status"))
        let centerBracket = output.components(separatedBy: "sketchybar --add bracket center_status").dropFirst().first ?? ""
        let centerMembers = centerBracket.split(separator: "\n").first.map(String.init) ?? ""
        XCTAssertTrue(centerMembers.contains("spotify_cover"))
        XCTAssertTrue(centerMembers.contains("spotify"))
        XCTAssertFalse(centerMembers.contains("spotify_group"))
    }

    func testRenderUsesSpotifyCoverSize() throws {
        var bar = BarSettings()
        bar.height = 52
        bar.spotifyCoverSize = 40

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("width=40"))
        XCTAssertTrue(output.contains("background.height=44"))
        XCTAssertTrue(output.contains("background.image.scale=0.0625"))
    }

    func testRenderSpotifyCoverSizeVariants() throws {
        let expectations: [(size: Int, barHeight: Int, width: String, height: String, scale: String)] = [
            (24, 40, "width=24", "background.height=32", "background.image.scale=0.0375"),
            (40, 52, "width=40", "background.height=44", "background.image.scale=0.0625"),
            (64, 80, "width=64", "background.height=72", "background.image.scale=0.1000"),
        ]

        for item in expectations {
            var bar = BarSettings()
            bar.height = item.barHeight
            bar.spotifyCoverSize = item.size
            let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
            XCTAssertTrue(output.contains(item.width), "size \(item.size): width")
            XCTAssertTrue(output.contains(item.height), "size \(item.size): height")
            XCTAssertTrue(output.contains(item.scale), "size \(item.size): scale")
        }
    }

    func testRenderSpotifyLabelMaxChars() throws {
        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: WidgetConfig.defaults))
        XCTAssertTrue(output.contains("label.max_chars=42"))
    }

    func testRenderOmitsSpotifyCoverWhenIconDisabled() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "spotify" }) {
            widgets[index].showIcon = false
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        XCTAssertFalse(output.contains("spotify_cover"))
        XCTAssertTrue(output.contains("sketchybar --add item spotify center"))
    }

    func testRenderSanitizesInvalidWidgetColor() throws {
        var widgets = WidgetConfig.defaults
        widgets[0].colorHex = "bad-color"

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        XCTAssertTrue(output.contains("label.color=\"\(SketchyBarColorHex.defaultWidgetColor)\""))
    }

    func testRenderSpotifyWidgetBackgroundUsesGroupBracket() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "spotify" }) {
            widgets[index].backgroundEnabled = true
            widgets[index].backgroundHex = "0xFFC97C5D"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let groupBlock = output.components(separatedBy: "sketchybar --add bracket spotify_group").dropFirst().first ?? ""
        XCTAssertTrue(groupBlock.contains("background.color=\"0xFFC97C5D\""))
        XCTAssertTrue(groupBlock.contains("background.drawing=on"))
    }

    func testRenderSpotifyCoverHasNoIndividualBackground() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "spotify" }) {
            widgets[index].backgroundEnabled = true
            widgets[index].backgroundHex = "0xFF606C38"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let coverSection = output.components(separatedBy: "sketchybar --add item spotify_cover").dropFirst().first ?? ""
        let coverBlock = coverSection.components(separatedBy: "sketchybar --add item spotify ").first ?? ""
        XCTAssertTrue(coverBlock.contains("background.drawing=on"))
        XCTAssertTrue(coverBlock.contains("background.color=\"0x00000000\""))
        XCTAssertFalse(coverBlock.contains("background.color=\"0xFF606C38\""))
    }

    func testRenderWidgetBackgroundDisabledExplicitlyOff() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "spotify" }) {
            widgets[index].backgroundEnabled = false
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let spotifyBlock = output.components(separatedBy: "sketchybar --add item spotify center").dropFirst().first ?? ""
        XCTAssertTrue(spotifyBlock.contains("background.drawing=off"))
    }

    func testRenderWidgetBackgroundEnabledForDate() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "date" }) {
            widgets[index].backgroundEnabled = true
            widgets[index].backgroundHex = "0xFFD8C3A5"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        XCTAssertTrue(output.contains("sketchybar --add item date center"))
        XCTAssertTrue(output.contains("background.color=\"0xFFD8C3A5\""))
    }

    func testRenderAppliesWidgetColorToLabelAndIcon() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "volume" }) {
            widgets[index].colorHex = "0xFF606C38"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let volumeBlock = output.components(separatedBy: "sketchybar --add item volume center").dropFirst().first ?? ""
        XCTAssertTrue(volumeBlock.contains("label.color=\"0xFF606C38\""))
        XCTAssertTrue(volumeBlock.contains("icon.color=\"0xFF606C38\""))
    }

    func testRenderAppliesWidgetColorToAudioOutput() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "audio_output" }) {
            widgets[index].colorHex = "0xFF9C6644"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let block = output.components(separatedBy: "sketchybar --add item audio_output center").dropFirst().first ?? ""
        XCTAssertTrue(block.contains("label.color=\"0xFF9C6644\""))
        XCTAssertTrue(block.contains("icon.color=\"0xFF9C6644\""))
        XCTAssertFalse(block.contains("icon.color=\"$ACCENT\""))
    }

    func testRenderBracketUsesSharedBackgroundWhenNoIndividualBackgrounds() throws {
        var widgets = WidgetConfig.defaults.map { widget -> WidgetConfig in
            var w = widget
            w.backgroundEnabled = false
            return w
        }
        widgets = widgets.filter { $0.id == "date" || $0.id == "clock" }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let bracketBlock = output.components(separatedBy: "sketchybar --add bracket center_status").dropFirst().first ?? ""
        XCTAssertTrue(bracketBlock.contains("background.drawing=on"))
        XCTAssertTrue(bracketBlock.contains("background.color=\"$PANEL_COLOR\""))
    }

    func testRenderBracketDisablesSharedBackgroundWhenIndividualBackgroundEnabled() throws {
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "date" }) {
            widgets[index].backgroundEnabled = true
            widgets[index].backgroundHex = "0xFFD8C3A5"
        }

        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: widgets))
        let bracketBlock = output.components(separatedBy: "sketchybar --add bracket center_status").dropFirst().first ?? ""
        XCTAssertTrue(bracketBlock.contains("background.drawing=off"))
        XCTAssertFalse(bracketBlock.contains("background.color=\"$PANEL_COLOR\""))
    }

    func testRenderDefaultsDisableCenterBracketWhenSpotifyBackgroundEnabled() throws {
        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: WidgetConfig.defaults))
        let bracketBlock = output.components(separatedBy: "sketchybar --add bracket center_status").dropFirst().first ?? ""
        XCTAssertTrue(bracketBlock.contains("background.drawing=off"))
    }

    func testRenderOmitsBackgroundPaddingKeys() throws {
        var bar = BarSettings()
        bar.widgetPadding = 4
        bar.itemSpacing = 8
        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertFalse(output.contains("background.padding_left"))
        XCTAssertFalse(output.contains("background.padding_right"))
    }

    func testRenderWidgetPaddingAndItemSpacingAreSeparate() throws {
        var bar = BarSettings()
        bar.widgetPadding = 4
        bar.itemSpacing = 8
        var widgets = WidgetConfig.defaults.filter { $0.id == "date" || $0.id == "clock" }
        for index in widgets.indices {
            widgets[index].backgroundEnabled = true
        }

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let dateBlock = output.components(separatedBy: "sketchybar --add item date center").dropFirst().first ?? ""
        XCTAssertTrue(dateBlock.contains("label.padding_left=4"))
        XCTAssertTrue(dateBlock.contains("label.padding_right=4"))
        XCTAssertTrue(dateBlock.contains("padding_right=8"))
        XCTAssertFalse(dateBlock.contains("padding_right=12"))
        XCTAssertFalse(output.contains("background.padding_left=4"))
    }

    func testRenderOddItemSpacingIsNotRounded() throws {
        var bar = BarSettings()
        bar.widgetPadding = 4
        bar.itemSpacing = 7
        var widgets = WidgetConfig.defaults.filter { $0.id == "date" || $0.id == "clock" }
        for index in widgets.indices {
            widgets[index].backgroundEnabled = true
        }

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let dateBlock = output.components(separatedBy: "sketchybar --add item date center").dropFirst().first ?? ""
        let clockBlock = output.components(separatedBy: "sketchybar --add item clock center").dropFirst().first ?? ""
        XCTAssertTrue(dateBlock.contains("padding_right=7"))
        XCTAssertTrue(dateBlock.contains("label.padding_right=4"))
        XCTAssertTrue(clockBlock.contains("padding_right=0"))

        let first = ItemLayoutMetrics.outerPadding(itemSpacing: 7, isFirst: true, isLast: false)
        let second = ItemLayoutMetrics.outerPadding(itemSpacing: 7, isFirst: false, isLast: true)
        XCTAssertEqual(ItemLayoutMetrics.gapBetweenCards(leftOuter: first, rightOuter: second), 7)
    }

    func testRenderAllCardHeightsMatch() throws {
        var widgets = WidgetConfig.defaults
        for index in widgets.indices where widgets[index].id != "umi_icon" {
            widgets[index].backgroundEnabled = true
        }
        let bar = BarSettings()
        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: widgets))
        let heights = layout.allWidgets.filter { $0.hasConfigurableBackground }.map(\.cardHeight)
        XCTAssertEqual(Set(heights).count, 1)
        XCTAssertEqual(heights.first, layout.cardHeight)

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let dateBlock = output.components(separatedBy: "sketchybar --add item date center").dropFirst().first ?? ""
        let volumeBlock = output.components(separatedBy: "sketchybar --add item volume center").dropFirst().first ?? ""
        let groupBlock = output.components(separatedBy: "sketchybar --add bracket spotify_group").dropFirst().first ?? ""
        XCTAssertTrue(dateBlock.contains("background.height=\(layout.cardHeight)"))
        XCTAssertTrue(volumeBlock.contains("background.height=\(layout.cardHeight)"))
        XCTAssertTrue(groupBlock.contains("background.height=\(layout.cardHeight)"))
        XCTAssertTrue(groupBlock.contains("background.corner_radius=\(layout.cardCornerRadius)"))
    }

    func testRenderClampsSpotifyCoverSizeToCardHeight() throws {
        var bar = BarSettings()
        bar.height = 40
        bar.spotifyCoverSize = 64
        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertEqual(layout.cardHeight, 32)
        XCTAssertEqual(layout.coverSize, 28)

        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        let coverBlock = output.components(separatedBy: "sketchybar --add item spotify_cover").dropFirst().first ?? ""
        XCTAssertTrue(coverBlock.contains("width=28"))
        XCTAssertFalse(coverBlock.contains("width=64"))
    }

    func testRenderSpotifyCoverBackgroundDrawingOn() throws {
        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: WidgetConfig.defaults))
        let coverBlock = output.components(separatedBy: "sketchybar --add item spotify_cover").dropFirst().first ?? ""
        XCTAssertTrue(coverBlock.contains("background.drawing=on"))
        XCTAssertTrue(coverBlock.contains("background.color=\"0x00000000\""))
    }

    func testRenderDoesNotNestSpotifyGroupInCenterStatus() throws {
        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: WidgetConfig.defaults))
        let membersLine = output
            .components(separatedBy: "sketchybar --add bracket center_status")
            .dropFirst()
            .first?
            .split(separator: "\n")
            .first
            .map(String.init) ?? ""
        XCTAssertTrue(membersLine.contains("spotify_cover"))
        XCTAssertTrue(membersLine.contains(" spotify"))
        XCTAssertFalse(membersLine.contains("spotify_group"))
        XCTAssertTrue(output.contains("sketchybar --reorder "))
        let reorderLine = output.components(separatedBy: "sketchybar --reorder ").dropFirst().first?
            .split(separator: "\n").first.map(String.init) ?? ""
        XCTAssertTrue(reorderLine.contains("spotify_cover"))
        XCTAssertFalse(reorderLine.contains("spotify_group"))
    }

    func testRenderIconItemUsesWidgetPaddingAndIconLabelGap() throws {
        var bar = BarSettings()
        bar.widgetPadding = 4
        var widgets = WidgetConfig.defaults
        if let index = widgets.firstIndex(where: { $0.id == "volume" }) {
            widgets[index].showIcon = true
        }
        let output = try TemplateRenderer.render(RenderInput(bar: bar, widgets: widgets))
        let volumeBlock = output.components(separatedBy: "sketchybar --add item volume center").dropFirst().first ?? ""
        XCTAssertTrue(volumeBlock.contains("icon.padding_left=4"))
        XCTAssertTrue(volumeBlock.contains("icon.padding_right=4"))
        XCTAssertTrue(volumeBlock.contains("label.padding_left=4"))
        XCTAssertTrue(volumeBlock.contains("label.padding_right=4"))
    }

    func testRenderTemplateDefaultIconPaddingIsZero() throws {
        let output = try TemplateRenderer.render(RenderInput(bar: BarSettings(), widgets: []))
        XCTAssertTrue(output.contains("icon.padding_left=0"))
        XCTAssertTrue(output.contains("icon.padding_right=0"))
        XCTAssertTrue(output.contains("label.padding_left=0"))
        XCTAssertTrue(output.contains("label.padding_right=0"))
    }
}

final class ItemLayoutMetricsTests: XCTestCase {
    func testOuterPaddingProducesExactGap() {
        let first = ItemLayoutMetrics.outerPadding(itemSpacing: 8, isFirst: true, isLast: false)
        let second = ItemLayoutMetrics.outerPadding(itemSpacing: 8, isFirst: false, isLast: true)
        XCTAssertEqual(first.left, 0)
        XCTAssertEqual(first.right, 8)
        XCTAssertEqual(second.left, 0)
        XCTAssertEqual(second.right, 0)
        XCTAssertEqual(ItemLayoutMetrics.gapBetweenCards(leftOuter: first, rightOuter: second), 8)
    }

    func testWidgetInnerPaddingSeparateFromItemSpacing() {
        XCTAssertEqual(ItemLayoutMetrics.widgetInnerPadding(4), 4)
        XCTAssertEqual(ItemLayoutMetrics.iconLabelGap, 4)
    }

    func testOddItemSpacingIsPreserved() {
        let first = ItemLayoutMetrics.outerPadding(itemSpacing: 7, isFirst: true, isLast: false)
        let second = ItemLayoutMetrics.outerPadding(itemSpacing: 7, isFirst: false, isLast: true)
        XCTAssertEqual(first.right, 7)
        XCTAssertEqual(second.left, 0)
        XCTAssertEqual(ItemLayoutMetrics.gapBetweenCards(leftOuter: first, rightOuter: second), 7)
    }
}

final class StyleResolverTests: XCTestCase {
    func testResolvedFontUsesBarDefaults() {
        var bar = BarSettings()
        bar.fontFamily = "Helvetica Neue"
        bar.fontSize = 14
        let widget = WidgetConfig(id: "date", name: "日付")

        XCTAssertEqual(StyleResolver.resolvedFontFamily(widget: widget, bar: bar), "Helvetica Neue")
        XCTAssertEqual(StyleResolver.resolvedFontSize(widget: widget, bar: bar), 14)
    }

    func testResolvedFontIgnoresWidgetOverride() {
        var bar = BarSettings()
        bar.fontFamily = "SF Pro Text"
        bar.fontSize = 13
        var widget = WidgetConfig(id: "date", name: "日付")
        widget.fontFamily = "UDEV Gothic 35JPDOC"
        widget.fontSize = 20

        XCTAssertEqual(StyleResolver.resolvedFontFamily(widget: widget, bar: bar), "SF Pro Text")
        XCTAssertEqual(StyleResolver.resolvedFontSize(widget: widget, bar: bar), 13)

        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: [widget]))
        XCTAssertEqual(layout.fontFamily, "SF Pro Text")
        XCTAssertEqual(layout.fontSize, 13)
        XCTAssertEqual(layout.center.first?.fontFamily, "SF Pro Text")
        XCTAssertEqual(layout.center.first?.fontSize, 13)
    }

    func testResolvedBackgroundMatchesRendererMetrics() {
        var bar = BarSettings()
        bar.height = 40
        bar.cornerRadius = 14
        let widget = WidgetConfig(id: "date", name: "日付", backgroundEnabled: true, backgroundHex: "0xFFD8C3A5")

        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: [widget]))
        XCTAssertEqual(layout.cardHeight, 32)
        XCTAssertEqual(layout.cardCornerRadius, 10)
        XCTAssertEqual(layout.center.first?.backgroundEnabled, true)
        XCTAssertEqual(layout.center.first?.backgroundHex, "0xFFD8C3A5")
        XCTAssertEqual(layout.center.first?.cardHeight, 32)
    }

    func testResolvedLayoutClampsCoverSize() {
        var bar = BarSettings()
        bar.height = 40
        bar.spotifyCoverSize = 64
        let layout = ResolvedBarLayout.make(from: RenderInput(bar: bar, widgets: WidgetConfig.defaults))
        XCTAssertEqual(layout.coverSize, min(64, layout.cardHeight - 4))
        XCTAssertEqual(layout.coverSize, 28)
        XCTAssertEqual(layout.center.first { $0.isSpotifyGroup }?.spotify?.coverSize, 28)
        XCTAssertEqual(layout.center.first { $0.isSpotifyGroup }?.cardHeight, layout.cardHeight)
    }

    func testResolvedLayoutDoesNotStoreSwiftUIColor() {
        let layout = ResolvedBarLayout.make(from: RenderInput(bar: BarSettings(), widgets: WidgetConfig.defaults))
        XCTAssertTrue(layout.barBackgroundHex.hasPrefix("0x"))
        XCTAssertEqual(layout.widgetPadding, 4)
        XCTAssertEqual(layout.itemSpacing, 6)
        XCTAssertEqual(layout.iconLabelGap, 4)
    }
}

final class EarthColorCatalogTests: XCTestCase {
    func testEarthColorPresetsAreValidHex() {
        for preset in EarthColorCatalog.presets {
            XCTAssertTrue(SketchyBarColorHex.isValid(preset.hex), preset.name)
        }
    }

    func testWhiteAndBlackPresets() {
        XCTAssertEqual(EarthColorCatalog.white, "0xFFFFFFFF")
        XCTAssertEqual(EarthColorCatalog.black, "0xFF000000")
        XCTAssertTrue(EarthColorCatalog.presets.contains { $0.id == "white" })
        XCTAssertTrue(EarthColorCatalog.presets.contains { $0.id == "black" })
    }

    func testEarthStylePresetsAreValidHex() {
        for preset in EarthColorCatalog.stylePresets {
            XCTAssertTrue(SketchyBarColorHex.isValid(preset.cardBackgroundHex), preset.name)
            XCTAssertTrue(SketchyBarColorHex.isValid(preset.textHex), preset.name)
            XCTAssertTrue(SketchyBarColorHex.isValid(preset.mutedTextHex), preset.name)
        }
    }

    func testStylePresetsIncludeWhiteText() {
        XCTAssertTrue(EarthColorCatalog.stylePresets.contains { $0.textHex == EarthColorCatalog.white })
    }

    func testStylePresetsIncludeRequiredNames() {
        let names = Set(EarthColorCatalog.stylePresets.map(\.name))
        XCTAssertEqual(names, ["砂丘", "テラコッタ", "森林", "海岸の石", "墨と砂"])
    }
}

final class SpotifyPluginTests: XCTestCase {
    func testBundledSpotifyShDoesNotOverrideCoverMetrics() throws {
        let url = BundledResources.spotifyScriptURL()
        XCTAssertNotNil(url)

        let script = try String(contentsOf: url!, encoding: .utf8)
        XCTAssertFalse(script.contains("background.image.scale="))
        XCTAssertFalse(script.contains("background.image.corner_radius="))
        XCTAssertFalse(script.contains("background.height="))
        XCTAssertFalse(script.contains("padding_left="))
        XCTAssertFalse(script.contains("padding_right="))
        XCTAssertFalse(script.contains("corner_radius="))
        XCTAssertTrue(script.contains("icon.drawing=on"))
        XCTAssertTrue(script.contains("background.drawing=on"))
        XCTAssertTrue(script.contains("--query spotify_cover"))
    }

    func testBundledSpotifyShDoesNotOverrideLabelColor() throws {
        let url = BundledResources.spotifyScriptURL()
        XCTAssertNotNil(url)

        let script = try String(contentsOf: url!, encoding: .utf8)
        XCTAssertFalse(script.contains("label.color="))
        XCTAssertFalse(script.contains("icon.color="))
    }

    func testBundledSpotifyShTurnsCoverAndTitleOnWhenPlaying() throws {
        let url = BundledResources.spotifyScriptURL()
        XCTAssertNotNil(url)
        let script = try String(contentsOf: url!, encoding: .utf8)
        XCTAssertTrue(script.contains("icon.drawing=on"))
        XCTAssertTrue(script.contains("background.drawing=on"))
        XCTAssertTrue(script.contains("background.image.drawing=on"))
        XCTAssertTrue(script.contains("drawing=on"))
        XCTAssertTrue(script.contains("--query spotify_cover"))
        XCTAssertFalse(script.contains("background.image.scale="))
        XCTAssertFalse(script.contains("label.color="))
    }
}

final class SketchyBarApplierTests: XCTestCase {
    func testApplyDoesNotRunRealCommands() throws {
        let runner = MockCommandRunner()
        let applier = SketchyBarApplier(runner: runner)
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let configPath = tempDir.appendingPathComponent("sketchybarrc").path

        try applier.apply(configuration: "# test", configPath: configPath)
        try applier.restartSketchyBar()

        XCTAssertTrue(FileManager.default.fileExists(atPath: configPath))
        XCTAssertEqual(runner.commands.count, 1)
        XCTAssertEqual(runner.commands.first?.0, "/opt/homebrew/bin/brew")
    }

    func testApplySyncsBundledSpotifyPlugin() throws {
        let applier = SketchyBarApplier()
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let pluginsDir = tempDir.appendingPathComponent("plugins").path

        try applier.syncBundledPlugins(to: pluginsDir)

        let pluginPath = (pluginsDir as NSString).appendingPathComponent("spotify.sh")
        XCTAssertTrue(FileManager.default.fileExists(atPath: pluginPath))
        let script = try String(contentsOf: URL(fileURLWithPath: pluginPath), encoding: .utf8)
        XCTAssertFalse(script.contains("background.image.scale="))
    }

    func testApplySyncsBundledSpotifyPluginWithExecutePermissions() throws {
        let applier = SketchyBarApplier()
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let pluginsDir = tempDir.appendingPathComponent("plugins").path

        try applier.syncBundledPlugins(to: pluginsDir)

        let pluginPath = (pluginsDir as NSString).appendingPathComponent("spotify.sh")
        let attributes = try FileManager.default.attributesOfItem(atPath: pluginPath)
        let permissions = (attributes[.posixPermissions] as? NSNumber)?.uint16Value ?? 0
        XCTAssertEqual(permissions & 0o111, 0o111)
    }
}
